<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Kaggle Notebooks - Predictive Modeling of Patient Status in Primary Biliary Cirrhosis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../pages/a-study-on-the-impact-of-feature-scaling.html" rel="prev">
<link href="../https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/189_Kaggle_logo_logos-1024.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<meta property="og:title" content="Kaggle Notebooks - Predictive Modeling of Patient Status in Primary Biliary Cirrhosis">
<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/f/fa/Primary_biliary_cirrhosis_intermed_mag_much_cropping.jpg">
<meta property="og:site-name" content="Kaggle Notebooks">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../pages/a-study-on-the-impact-of-feature-scaling.html">Notebooks</a></li><li class="breadcrumb-item"><a href="../pages/pg-s3e26.html">playground-s3e26</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/189_Kaggle_logo_logos-1024.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://github.com/SherryS997/kaggle-notebook" rel="" title="GitHub Repo" class="quarto-navigation-tool px-1" aria-label="GitHub Repo"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Home</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Notebooks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/a-study-on-the-impact-of-feature-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Feature Scaling Impact</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/pg-s3e26.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">playground-s3e26</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-dataset-overview" id="toc-introduction-and-dataset-overview" class="nav-link active" data-scroll-target="#introduction-and-dataset-overview">Introduction and Dataset Overview</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective">Objective</a></li>
  <li><a href="#dataset-overview" id="toc-dataset-overview" class="nav-link" data-scroll-target="#dataset-overview">Dataset Overview</a></li>
  </ul></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">Data Exploration</a>
  <ul class="collapse">
  <li><a href="#dataset-snapshot" id="toc-dataset-snapshot" class="nav-link" data-scroll-target="#dataset-snapshot">Dataset Snapshot</a></li>
  <li><a href="#dataset-information-summary" id="toc-dataset-information-summary" class="nav-link" data-scroll-target="#dataset-information-summary">Dataset Information Summary</a></li>
  <li><a href="#statistical-summary-of-the-dataset" id="toc-statistical-summary-of-the-dataset" class="nav-link" data-scroll-target="#statistical-summary-of-the-dataset">Statistical Summary of the Dataset</a></li>
  <li><a href="#pie-plot-analysis" id="toc-pie-plot-analysis" class="nav-link" data-scroll-target="#pie-plot-analysis">Pie Plot Analysis</a></li>
  <li><a href="#status-distribution" id="toc-status-distribution" class="nav-link" data-scroll-target="#status-distribution">Status Distribution</a></li>
  <li><a href="#categorical-variable-distributions-train-and-test-sets" id="toc-categorical-variable-distributions-train-and-test-sets" class="nav-link" data-scroll-target="#categorical-variable-distributions-train-and-test-sets">Categorical Variable Distributions (Train and Test Sets)</a></li>
  </ul></li>
  <li><a href="#data-preprocessing" id="toc-data-preprocessing" class="nav-link" data-scroll-target="#data-preprocessing">Data Preprocessing</a>
  <ul class="collapse">
  <li><a href="#one-hot-encoding-and-data-preparation" id="toc-one-hot-encoding-and-data-preparation" class="nav-link" data-scroll-target="#one-hot-encoding-and-data-preparation">One-Hot Encoding and Data Preparation</a></li>
  <li><a href="#one-hot-encoding-categorical-variables" id="toc-one-hot-encoding-categorical-variables" class="nav-link" data-scroll-target="#one-hot-encoding-categorical-variables">One-Hot Encoding Categorical Variables</a></li>
  <li><a href="#feature-target-splitting" id="toc-feature-target-splitting" class="nav-link" data-scroll-target="#feature-target-splitting">Feature-Target Splitting</a></li>
  <li><a href="#handling-missing-values-simpleimputer" id="toc-handling-missing-values-simpleimputer" class="nav-link" data-scroll-target="#handling-missing-values-simpleimputer">Handling Missing Values: SimpleImputer</a>
  <ul class="collapse">
  <li><a href="#simpleimputer-explanation" id="toc-simpleimputer-explanation" class="nav-link" data-scroll-target="#simpleimputer-explanation">SimpleImputer Explanation:</a></li>
  <li><a href="#application-of-simpleimputer" id="toc-application-of-simpleimputer" class="nav-link" data-scroll-target="#application-of-simpleimputer">Application of SimpleImputer:</a></li>
  </ul></li>
  <li><a href="#scaling-using-robustscaler" id="toc-scaling-using-robustscaler" class="nav-link" data-scroll-target="#scaling-using-robustscaler">Scaling using RobustScaler</a></li>
  <li><a href="#robustscaler-explanation" id="toc-robustscaler-explanation" class="nav-link" data-scroll-target="#robustscaler-explanation">RobustScaler Explanation:</a></li>
  <li><a href="#application-of-robustscaler" id="toc-application-of-robustscaler" class="nav-link" data-scroll-target="#application-of-robustscaler">Application of RobustScaler:</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#correlation-analysis" id="toc-correlation-analysis" class="nav-link" data-scroll-target="#correlation-analysis">Correlation Analysis</a></li>
  </ul></li>
  <li><a href="#model-building" id="toc-model-building" class="nav-link" data-scroll-target="#model-building">Model Building</a>
  <ul class="collapse">
  <li><a href="#cross-validation-and-train-test-split" id="toc-cross-validation-and-train-test-split" class="nav-link" data-scroll-target="#cross-validation-and-train-test-split">Cross-validation and Train-Test Split</a></li>
  <li><a href="#stratified-k-fold-cross-validation" id="toc-stratified-k-fold-cross-validation" class="nav-link" data-scroll-target="#stratified-k-fold-cross-validation">Stratified K-Fold Cross-Validation</a></li>
  <li><a href="#train-test-split" id="toc-train-test-split" class="nav-link" data-scroll-target="#train-test-split">Train-Test Split</a></li>
  <li><a href="#training-multiple-lightgbm-models-with-cross-validation" id="toc-training-multiple-lightgbm-models-with-cross-validation" class="nav-link" data-scroll-target="#training-multiple-lightgbm-models-with-cross-validation">Training Multiple LightGBM Models with Cross-Validation</a></li>
  <li><a href="#training-multiple-xgboost-models-with-cross-validation" id="toc-training-multiple-xgboost-models-with-cross-validation" class="nav-link" data-scroll-target="#training-multiple-xgboost-models-with-cross-validation">Training Multiple XGBoost Models with Cross-Validation</a></li>
  <li><a href="#training-catboost-models-and-evaluating-performance" id="toc-training-catboost-models-and-evaluating-performance" class="nav-link" data-scroll-target="#training-catboost-models-and-evaluating-performance">Training CatBoost Models and Evaluating Performance</a></li>
  <li><a href="#elevating-predictive-power-with-stacked-ensemble-model" id="toc-elevating-predictive-power-with-stacked-ensemble-model" class="nav-link" data-scroll-target="#elevating-predictive-power-with-stacked-ensemble-model">Elevating Predictive Power with Stacked Ensemble Model</a></li>
  <li><a href="#model-configuration" id="toc-model-configuration" class="nav-link" data-scroll-target="#model-configuration">Model Configuration:</a></li>
  <li><a href="#stackingclassifier-configuration" id="toc-stackingclassifier-configuration" class="nav-link" data-scroll-target="#stackingclassifier-configuration">StackingClassifier Configuration:</a></li>
  <li><a href="#implementation" id="toc-implementation" class="nav-link" data-scroll-target="#implementation">Implementation:</a></li>
  <li><a href="#explanation" id="toc-explanation" class="nav-link" data-scroll-target="#explanation">Explanation:</a></li>
  </ul></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation">Model Evaluation</a>
  <ul class="collapse">
  <li><a href="#evaluating-stacked-ensemble-model-performance" id="toc-evaluating-stacked-ensemble-model-performance" class="nav-link" data-scroll-target="#evaluating-stacked-ensemble-model-performance">Evaluating Stacked Ensemble Model Performance</a></li>
  <li><a href="#model-evaluation-metrics" id="toc-model-evaluation-metrics" class="nav-link" data-scroll-target="#model-evaluation-metrics">Model Evaluation Metrics:</a></li>
  <li><a href="#evaluation-metrics-computed" id="toc-evaluation-metrics-computed" class="nav-link" data-scroll-target="#evaluation-metrics-computed">Evaluation Metrics Computed:</a></li>
  <li><a href="#confusion-matrix-and-classification-report" id="toc-confusion-matrix-and-classification-report" class="nav-link" data-scroll-target="#confusion-matrix-and-classification-report">Confusion Matrix and Classification Report:</a></li>
  <li><a href="#evaluation-process-and-metrics-computation" id="toc-evaluation-process-and-metrics-computation" class="nav-link" data-scroll-target="#evaluation-process-and-metrics-computation">Evaluation Process and Metrics Computation:</a></li>
  <li><a href="#insights-from-evaluation-metrics" id="toc-insights-from-evaluation-metrics" class="nav-link" data-scroll-target="#insights-from-evaluation-metrics">Insights from Evaluation Metrics:</a></li>
  <li><a href="#detailed-class-wise-performance" id="toc-detailed-class-wise-performance" class="nav-link" data-scroll-target="#detailed-class-wise-performance">Detailed Class-wise Performance:</a>
  <ul class="collapse">
  <li><a href="#class-0" id="toc-class-0" class="nav-link" data-scroll-target="#class-0">Class 0:</a></li>
  <li><a href="#class-1" id="toc-class-1" class="nav-link" data-scroll-target="#class-1">Class 1:</a></li>
  <li><a href="#class-2" id="toc-class-2" class="nav-link" data-scroll-target="#class-2">Class 2:</a></li>
  </ul></li>
  <li><a href="#overall-summary" id="toc-overall-summary" class="nav-link" data-scroll-target="#overall-summary">Overall Summary:</a></li>
  </ul></li>
  <li><a href="#conclusion-and-future-steps" id="toc-conclusion-and-future-steps" class="nav-link" data-scroll-target="#conclusion-and-future-steps">Conclusion and Future Steps</a>
  <ul class="collapse">
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">Key Findings</a></li>
  <li><a href="#insights-for-improvement" id="toc-insights-for-improvement" class="nav-link" data-scroll-target="#insights-for-improvement">Insights for Improvement</a></li>
  <li><a href="#future-steps" id="toc-future-steps" class="nav-link" data-scroll-target="#future-steps">Future Steps</a></li>
  <li><a href="#final-note" id="toc-final-note" class="nav-link" data-scroll-target="#final-note">Final Note</a></li>
  </ul></li>
  <li><a href="#generating-predictions-for-test-data" id="toc-generating-predictions-for-test-data" class="nav-link" data-scroll-target="#generating-predictions-for-test-data">Generating Predictions for Test Data</a></li>
  <li><a href="#credits" id="toc-credits" class="nav-link" data-scroll-target="#credits">Credits</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.dev/SherryS997/kaggle-notebook/blob/main/pages/pg-s3e26.ipynb" class="toc-action">Edit this page</a></p><p><a href="https://github.com/SherryS997/kaggle-notebook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predictive Modeling of Patient Status in Primary Biliary Cirrhosis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction-and-dataset-overview" class="level1">
<h1>Introduction and Dataset Overview</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/f/fa/Primary_biliary_cirrhosis_intermed_mag_much_cropping.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Micrograph of PBC showing bile duct inflammation and injury, H&amp;E stain</figcaption>
</figure>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Cirrhosis stands as a severe consequence of liver diseases, where extensive scarring compromises liver function. The dataset at hand is inspired from a dataset by the Mayo Clinic’s trial addressing primary biliary cirrhosis (PBC) during 1974-1984. The original data encompasses crucial insights gleaned from 424 PBC patients, marking a pivotal endeavor in understanding the clinical landscape of this condition.</p>
<p>The original dataset, meticulously gathered as part of a randomized placebo-controlled trial involving D-penicillamine, presents a comprehensive array of covariates. Each entry comprises fundamental patient attributes, ranging from clinical measurements to key indicators of liver health.</p>
</section>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
<p>The primary aim of this notebook is to harness machine learning methodologies to predict the status of PBC patients based on a diverse set of features. The ‘Status’ variable, delineated as C (censored), CL (censored due to liver tx), or D (death), serves as the focal point for predictive modeling. Leveraging the patient-specific attributes provided, the goal is to construct robust predictive models capable of discerning and forecasting patient outcomes within the scope of the study period.</p>
</section>
<section id="dataset-overview" class="level2">
<h2 class="anchored" data-anchor-id="dataset-overview">Dataset Overview</h2>
<ol type="1">
<li><strong>Size:</strong> The dataset contains information on 7905 PBC patients, amalgamating both trial participants and supplementary cases with recorded measurements.</li>
<li><strong>Features:</strong> Comprising 19 attributes encompassing a spectrum of patient-related variables, including demographic data, clinical measurements, and indicators of liver health.</li>
<li><strong>Context:</strong> The features encapsulate critical facets of patient health, such as age, sex, presence of specific symptoms (ascites, hepatomegaly, spiders, edema), laboratory test results (bilirubin, cholesterol, albumin, copper, alkaline phosphatase, SGOT, triglycerides, platelets, prothrombin), and histologic staging of the disease.</li>
</ol>
<p>Throughout this notebook, we embark on a journey through data exploration, preprocessing, model selection, and evaluation, culminating in the development of predictive models aimed at discerning and forecasting the status of PBC patients.</p>
<p>Let’s delve into the intricate realm of predictive modeling in the context of primary biliary cirrhosis, unraveling insights and patterns within this comprehensive dataset.</p>
</section>
</section>
<section id="data-exploration" class="level1">
<h1>Data Exploration</h1>
<section id="dataset-snapshot" class="level2">
<h2 class="anchored" data-anchor-id="dataset-snapshot">Dataset Snapshot</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:37.699960Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:37.699618Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:39.298317Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:39.297064Z&quot;}" data-papermill="{&quot;duration&quot;:1.615464,&quot;end_time&quot;:&quot;2023-12-31T05:49:39.300969&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:37.685505&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(<span class="st">'/kaggle/input/playground-series-s3e26/train.csv'</span>, index_col<span class="op">=</span><span class="st">'id'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>test_df <span class="op">=</span> pd.read_csv(<span class="st">'/kaggle/input/playground-series-s3e26/test.csv'</span>, index_col<span class="op">=</span><span class="st">'id'</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>orig_df <span class="op">=</span> pd.read_csv(<span class="st">"/kaggle/input/cirrhosis-prediction-dataset/cirrhosis.csv"</span>, index_col<span class="op">=</span><span class="st">"ID"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.concat([orig_df, data], axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">N_Days</th>
<th data-quarto-table-cell-role="th">Status</th>
<th data-quarto-table-cell-role="th">Drug</th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Sex</th>
<th data-quarto-table-cell-role="th">Ascites</th>
<th data-quarto-table-cell-role="th">Hepatomegaly</th>
<th data-quarto-table-cell-role="th">Spiders</th>
<th data-quarto-table-cell-role="th">Edema</th>
<th data-quarto-table-cell-role="th">Bilirubin</th>
<th data-quarto-table-cell-role="th">Cholesterol</th>
<th data-quarto-table-cell-role="th">Albumin</th>
<th data-quarto-table-cell-role="th">Copper</th>
<th data-quarto-table-cell-role="th">Alk_Phos</th>
<th data-quarto-table-cell-role="th">SGOT</th>
<th data-quarto-table-cell-role="th">Tryglicerides</th>
<th data-quarto-table-cell-role="th">Platelets</th>
<th data-quarto-table-cell-role="th">Prothrombin</th>
<th data-quarto-table-cell-role="th">Stage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>400</td>
<td>D</td>
<td>D-penicillamine</td>
<td>21464</td>
<td>F</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>14.5</td>
<td>261.0</td>
<td>2.60</td>
<td>156.0</td>
<td>1718.0</td>
<td>137.95</td>
<td>172.0</td>
<td>190.0</td>
<td>12.2</td>
<td>4.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>4500</td>
<td>C</td>
<td>D-penicillamine</td>
<td>20617</td>
<td>F</td>
<td>N</td>
<td>Y</td>
<td>Y</td>
<td>N</td>
<td>1.1</td>
<td>302.0</td>
<td>4.14</td>
<td>54.0</td>
<td>7394.8</td>
<td>113.52</td>
<td>88.0</td>
<td>221.0</td>
<td>10.6</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>1012</td>
<td>D</td>
<td>D-penicillamine</td>
<td>25594</td>
<td>M</td>
<td>N</td>
<td>N</td>
<td>N</td>
<td>S</td>
<td>1.4</td>
<td>176.0</td>
<td>3.48</td>
<td>210.0</td>
<td>516.0</td>
<td>96.10</td>
<td>55.0</td>
<td>151.0</td>
<td>12.0</td>
<td>4.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>1925</td>
<td>D</td>
<td>D-penicillamine</td>
<td>19994</td>
<td>F</td>
<td>N</td>
<td>Y</td>
<td>Y</td>
<td>S</td>
<td>1.8</td>
<td>244.0</td>
<td>2.54</td>
<td>64.0</td>
<td>6121.8</td>
<td>60.63</td>
<td>92.0</td>
<td>183.0</td>
<td>10.3</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>1504</td>
<td>CL</td>
<td>Placebo</td>
<td>13918</td>
<td>F</td>
<td>N</td>
<td>Y</td>
<td>Y</td>
<td>N</td>
<td>3.4</td>
<td>279.0</td>
<td>3.53</td>
<td>143.0</td>
<td>671.0</td>
<td>113.15</td>
<td>72.0</td>
<td>136.0</td>
<td>10.9</td>
<td>3.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The initial entries of the dataset, as revealed by the <code>train.head()</code> command, offer a glimpse into the fundamental attributes and features characterizing the primary biliary cirrhosis (PBC) dataset. These entries encompass a diverse range of patient-related information, providing crucial insights into the condition and status of the individuals under study.</p>
<p><strong>Attributes Overview:</strong></p>
<ol type="1">
<li><strong>ID:</strong> A unique identifier assigned to each patient within the dataset.</li>
<li><strong>N_Days:</strong> The number of days between registration and the earlier occurrence of death, liver transplantation, or the study analysis time in July 1986.</li>
<li><strong>Status:</strong> Categorization of the patient’s status denoted as C (censored), CL (censored due to liver tx), or D (death).</li>
<li><strong>Drug:</strong> Indicates the type of drug administered to the patient, specifying either D-penicillamine or Placebo.</li>
<li><strong>Age:</strong> Age of the patient represented in days.</li>
<li><strong>Sex:</strong> Gender classification denoted as M (male) or F (female).</li>
<li><strong>Ascites:</strong> Presence or absence of ascites, indicated by Y (Yes) or N (No), respectively.</li>
<li><strong>Hepatomegaly:</strong> Identification of hepatomegaly, denoted by Y (Yes) or N (No).</li>
<li><strong>Spiders:</strong> Presence or absence of spiders, indicating Y (Yes) or N (No), respectively.</li>
<li><strong>Edema:</strong> Details the presence and management of edema, categorized as S (edema present without diuretics, or edema resolved by diuretics), Y (edema despite diuretic therapy), or N (no edema and no diuretic therapy for edema).</li>
<li><strong>Bilirubin:</strong> Serum bilirubin levels measured in mg/dl.</li>
<li><strong>Cholesterol:</strong> Serum cholesterol levels measured in mg/dl.</li>
<li><strong>Albumin:</strong> Albumin levels in gm/dl.</li>
<li><strong>Copper:</strong> Urine copper levels recorded in ug/day.</li>
<li><strong>Alk_Phos:</strong> Alkaline phosphatase levels in U/liter.</li>
<li><strong>SGOT:</strong> SGOT (Serum Glutamic Oxaloacetic Transaminase) levels measured in U/ml.</li>
<li><strong>Tryglicerides:</strong> Triglyceride levels measured in mg/dl.</li>
<li><strong>Platelets:</strong> Platelet count per cubic ml/1000.</li>
<li><strong>Prothrombin:</strong> Prothrombin time measured in seconds (s).</li>
<li><strong>Stage:</strong> Histologic stage of the disease categorized as 1, 2, 3, or 4.</li>
</ol>
<p>This snapshot serves as a foundational view of the dataset, highlighting the diverse array of attributes and their corresponding values that will be further explored, analyzed, and utilized in the predictive modeling and analysis undertaken in this notebook.</p>
</section>
<section id="dataset-information-summary" class="level2">
<h2 class="anchored" data-anchor-id="dataset-information-summary">Dataset Information Summary</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:39.433601Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:39.433236Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:39.534715Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:39.533794Z&quot;}" data-papermill="{&quot;duration&quot;:0.118048,&quot;end_time&quot;:&quot;2023-12-31T05:49:39.536993&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:39.418945&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Index: 8323 entries, 1 to 7904
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   N_Days         8323 non-null   int64  
 1   Status         8323 non-null   object 
 2   Drug           8217 non-null   object 
 3   Age            8323 non-null   int64  
 4   Sex            8323 non-null   object 
 5   Ascites        8217 non-null   object 
 6   Hepatomegaly   8217 non-null   object 
 7   Spiders        8217 non-null   object 
 8   Edema          8323 non-null   object 
 9   Bilirubin      8323 non-null   float64
 10  Cholesterol    8189 non-null   float64
 11  Albumin        8323 non-null   float64
 12  Copper         8215 non-null   float64
 13  Alk_Phos       8217 non-null   float64
 14  SGOT           8217 non-null   float64
 15  Tryglicerides  8187 non-null   float64
 16  Platelets      8312 non-null   float64
 17  Prothrombin    8321 non-null   float64
 18  Stage          8317 non-null   float64
dtypes: float64(10), int64(2), object(7)
memory usage: 1.3+ MB</code></pre>
</div>
</div>
<p>The dataset comprises a total of 7905 entries, each corresponding to a distinct patient record. There are 19 columns, each representing specific attributes or features related to the patients’ medical history and condition.</p>
<p><strong>Insights from the Data Columns:</strong></p>
<ol type="1">
<li><p><strong>Categorical Variables:</strong> Several columns in the dataset are categorized as object data type, indicating categorical information. These columns include ‘Drug,’ ‘Ascites,’ ‘Hepatomegaly,’ ‘Spiders,’ ‘Edema,’ and ‘Status.’ Notably, ‘Drug,’ ‘Ascites,’ ‘Hepatomegaly,’ and ‘Spiders’ exhibit non-null counts of 7905, implying no missing values in these categorical attributes.</p></li>
<li><p><strong>Numerical Variables:</strong> The dataset also contains numerical variables, delineated by float64 and int64 data types. These columns encompass clinical measurements, patient-specific details like age, laboratory test results, and disease stage. Interestingly, attributes such as ‘Cholesterol,’ ‘Copper,’ ‘Alk_Phos,’ ‘SGOT,’ ‘Tryglicerides,’ ‘Platelets,’ ‘Prothrombin,’ and ‘Stage’ also exhibit non-null counts of 7905, suggesting a lack of missing values in these numerical features.</p></li>
</ol>
<p><strong>Memory Utilization:</strong></p>
<p>The dataset’s memory usage is estimated to be over 1.2 MB, highlighting the computational footprint required to store this dataset in memory.</p>
<p><strong>Data Completeness and Challenges:</strong></p>
<p>Surprisingly, based on the updated information, it appears that there are no missing values across any of the columns in this dataset. This completeness diminishes the need for immediate data imputation or handling missing values during the preprocessing stage.</p>
</section>
<section id="statistical-summary-of-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="statistical-summary-of-the-dataset">Statistical Summary of the Dataset</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:39.617054Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:39.616671Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:39.659351Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:39.658431Z&quot;}" data-papermill="{&quot;duration&quot;:0.05897,&quot;end_time&quot;:&quot;2023-12-31T05:49:39.661347&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:39.602377&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">N_Days</th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Bilirubin</th>
<th data-quarto-table-cell-role="th">Cholesterol</th>
<th data-quarto-table-cell-role="th">Albumin</th>
<th data-quarto-table-cell-role="th">Copper</th>
<th data-quarto-table-cell-role="th">Alk_Phos</th>
<th data-quarto-table-cell-role="th">SGOT</th>
<th data-quarto-table-cell-role="th">Tryglicerides</th>
<th data-quarto-table-cell-role="th">Platelets</th>
<th data-quarto-table-cell-role="th">Prothrombin</th>
<th data-quarto-table-cell-role="th">Stage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>8323.000000</td>
<td>8323.000000</td>
<td>8323.000000</td>
<td>8189.000000</td>
<td>8323.000000</td>
<td>8215.000000</td>
<td>8217.000000</td>
<td>8217.000000</td>
<td>8187.000000</td>
<td>8312.000000</td>
<td>8321.000000</td>
<td>8317.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>2024.528776</td>
<td>18381.192359</td>
<td>2.625940</td>
<td>351.219074</td>
<td>3.545767</td>
<td>84.421546</td>
<td>1823.044883</td>
<td>114.906530</td>
<td>115.662636</td>
<td>264.827238</td>
<td>10.634575</td>
<td>3.032103</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>1094.968696</td>
<td>3686.832308</td>
<td>3.847146</td>
<td>196.775246</td>
<td>0.350697</td>
<td>76.327480</td>
<td>1913.388685</td>
<td>49.134067</td>
<td>53.037660</td>
<td>88.039809</td>
<td>0.795707</td>
<td>0.867235</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>41.000000</td>
<td>9598.000000</td>
<td>0.300000</td>
<td>120.000000</td>
<td>1.960000</td>
<td>4.000000</td>
<td>289.000000</td>
<td>26.350000</td>
<td>33.000000</td>
<td>62.000000</td>
<td>9.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1220.000000</td>
<td>15574.000000</td>
<td>0.700000</td>
<td>248.000000</td>
<td>3.350000</td>
<td>39.000000</td>
<td>834.000000</td>
<td>75.950000</td>
<td>84.000000</td>
<td>210.000000</td>
<td>10.000000</td>
<td>2.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>1831.000000</td>
<td>18713.000000</td>
<td>1.100000</td>
<td>299.000000</td>
<td>3.580000</td>
<td>63.000000</td>
<td>1181.000000</td>
<td>108.500000</td>
<td>104.000000</td>
<td>264.000000</td>
<td>10.600000</td>
<td>3.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>2689.000000</td>
<td>20684.000000</td>
<td>3.000000</td>
<td>392.000000</td>
<td>3.770000</td>
<td>102.000000</td>
<td>1857.000000</td>
<td>137.950000</td>
<td>139.000000</td>
<td>316.000000</td>
<td>11.000000</td>
<td>4.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>4795.000000</td>
<td>28650.000000</td>
<td>28.000000</td>
<td>1775.000000</td>
<td>4.640000</td>
<td>588.000000</td>
<td>13862.400000</td>
<td>457.250000</td>
<td>598.000000</td>
<td>721.000000</td>
<td>18.000000</td>
<td>4.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The statistical summary provides comprehensive information regarding the numerical columns within the dataset, offering insights into the central tendencies, dispersion, and distribution of various clinical measurements and patient-specific attributes.</p>
<p><strong>Key Observations:</strong></p>
<ol type="1">
<li><p><strong>Count:</strong> Each column’s count indicates the number of non-null entries for the corresponding attribute. Consistent counts across columns suggest no missing values for any of the numerical features.</p></li>
<li><p><strong>Central Tendencies:</strong></p>
<ul>
<li><p><strong>N_Days (Number of Days):</strong> The average time between registration and events (death, transplantation, or study analysis) stands at approximately 2030.17 days, with a wide range from 41 days to 4795 days, highlighting significant variability in the duration between events across patients.</p></li>
<li><p><strong>Age:</strong> The average age in days is approximately 18373.15, ranging from a minimum of 9598 days to a maximum of 28650 days, demonstrating a diverse age distribution among patients in the dataset.</p></li>
<li><p><strong>Clinical Measurements:</strong> Various clinical measurements such as bilirubin, cholesterol, albumin, copper, alkaline phosphatase (Alk_Phos), SGOT, triglycerides, platelets, prothrombin, and disease stage (Stage) exhibit diverse mean values and ranges, indicating variability in patient conditions and responses to treatment.</p></li>
</ul></li>
<li><p><strong>Dispersion:</strong></p>
<ul>
<li><strong>Standard Deviation:</strong> Standard deviations for attributes like bilirubin, cholesterol, Alk_Phos, SGOT, and others are relatively high, signifying considerable variability or spread of values around their respective means across the patient population.</li>
</ul></li>
<li><p><strong>Minimum, Maximum, and Quartiles:</strong></p>
<ul>
<li><p>The minimum and maximum values denote the range observed within each attribute, showcasing the extremes of values in the dataset.</p></li>
<li><p>Quartiles (25%, 50%, and 75%) offer insights into the distribution of values, showcasing the spread of data and potential presence of outliers within each numerical variable.</p></li>
</ul></li>
</ol>
<p><strong>Data Interpretation:</strong></p>
<ul>
<li><p>The wide range of values across different clinical measurements and patient-specific attributes underlines the diversity and variability in patient conditions within the PBC dataset.</p></li>
<li><p>Notably, based on this summary, there appear to be no missing values in any of the numerical columns. This completeness minimizes the immediate need for data imputation or handling of missing values during the preprocessing stage.</p></li>
</ul>
<p>This statistical summary serves as a foundational step for further exploration, analysis, and potential model development, providing insights crucial for feature engineering and robust model building in subsequent stages of the analysis.</p>
</section>
<section id="pie-plot-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pie-plot-analysis">Pie Plot Analysis</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:39.742244Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:39.741872Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:39.750982Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:39.750121Z&quot;}" data-papermill="{&quot;duration&quot;:0.026411,&quot;end_time&quot;:&quot;2023-12-31T05:49:39.753391&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:39.726980&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cat_cols <span class="op">=</span> data.drop([<span class="st">"Status"</span>], axis<span class="op">=</span><span class="dv">1</span>).select_dtypes(include<span class="op">=</span><span class="st">'object'</span>).columns.tolist()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>num_cols <span class="op">=</span> data.select_dtypes(exclude<span class="op">=</span><span class="st">'object'</span>).columns.tolist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:39.782678Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:39.782000Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:39.798458Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:39.797445Z&quot;}" data-papermill="{&quot;duration&quot;:0.033761,&quot;end_time&quot;:&quot;2023-12-31T05:49:39.800734&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:39.766973&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_target(data: pd.DataFrame, col: <span class="bu">str</span>, title: <span class="bu">str</span>, pie_colors: <span class="bu">list</span>, test_df: pd.DataFrame <span class="op">=</span> pd.DataFrame()) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> test_df.empty:</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>        fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">6</span>), gridspec_kw<span class="op">=</span>{<span class="st">'width_ratios'</span>: [<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>]})</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i, data <span class="kw">in</span> <span class="bu">enumerate</span>([data, test_df]):</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>            textprops<span class="op">=</span>{<span class="st">'fontsize'</span>: <span class="dv">12</span>, <span class="st">'weight'</span>: <span class="st">'bold'</span>, <span class="st">'color'</span>: <span class="st">'black'</span>}</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>            ax <span class="op">=</span> axes[i <span class="op">*</span> <span class="dv">2</span>]</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>            ax.pie(data[col].value_counts().to_list(),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>                colors<span class="op">=</span>pie_colors,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                labels<span class="op">=</span>data[col].value_counts().index.to_list(),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>                autopct<span class="op">=</span><span class="st">'%1.f</span><span class="sc">%%</span><span class="st">'</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>                explode<span class="op">=</span>([<span class="fl">.05</span>] <span class="op">*</span> data[col].nunique()),</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                pctdistance<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                wedgeprops<span class="op">=</span>{<span class="st">'linewidth'</span>: <span class="dv">1</span>, <span class="st">'edgecolor'</span>: <span class="st">'black'</span>},</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                textprops<span class="op">=</span>textprops)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>            sns.countplot(x<span class="op">=</span>col, data<span class="op">=</span>data, palette<span class="op">=</span><span class="st">'pastel6'</span>, hue<span class="op">=</span>col, order<span class="op">=</span>data[col].value_counts().to_dict().keys(), ax<span class="op">=</span>axes[i <span class="op">*</span> <span class="dv">2</span> <span class="op">+</span> <span class="dv">1</span>])</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> p, count <span class="kw">in</span> <span class="bu">enumerate</span>(data[col].value_counts().to_dict().values(), <span class="dv">0</span>):</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>                axes[i <span class="op">*</span> <span class="dv">2</span> <span class="op">+</span> <span class="dv">1</span>].text(p <span class="op">-</span> <span class="fl">0.1</span>, count <span class="op">+</span> (np.sqrt(count)), count, color<span class="op">=</span><span class="st">'black'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>            plt.setp(axes[i <span class="op">*</span> <span class="dv">2</span> <span class="op">+</span> <span class="dv">1</span>].get_xticklabels(), fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>            plt.yticks([], ax<span class="op">=</span>axes[i <span class="op">*</span> <span class="dv">2</span> <span class="op">+</span> <span class="dv">1</span>])</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>            axes[i <span class="op">*</span> <span class="dv">2</span> <span class="op">+</span> <span class="dv">1</span>].set_ylabel(<span class="st">''</span>)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>            axes[i <span class="op">*</span> <span class="dv">2</span> <span class="op">+</span> <span class="dv">1</span>].set_xlabel(<span class="st">''</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>            <span class="co"># axes[i * 2 + 1].get_legend().remove()</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>            <span class="co"># plt.box(False, ax=axes[i * 2 + 1])</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>            axes[i <span class="op">*</span> <span class="dv">2</span>].set_title(<span class="ss">f'Distribution in </span><span class="sc">{</span><span class="st">"Train"</span> <span class="cf">if</span> i <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">"Test"</span><span class="sc">}</span><span class="ss"> Set'</span>, fontsize<span class="op">=</span><span class="dv">16</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>        fig.suptitle(x<span class="op">=</span><span class="fl">0.5</span>, y<span class="op">=</span><span class="fl">1.05</span>, t<span class="op">=</span><span class="ss">f'► </span><span class="sc">{</span>title<span class="sc">}</span><span class="ss"> Distribution ◄'</span>, fontsize<span class="op">=</span><span class="dv">18</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>        plt.tight_layout()</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>        plt.show()</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>        fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>,figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">6</span>), width_ratios<span class="op">=</span>[<span class="dv">2</span>,<span class="dv">1</span>])</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>        textprops<span class="op">=</span>{<span class="st">'fontsize'</span>: <span class="dv">12</span>, <span class="st">'weight'</span>: <span class="st">'bold'</span>,<span class="st">"color"</span>: <span class="st">"black"</span>}</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>        ax[<span class="dv">0</span>].pie(data[col].value_counts().to_list(),</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>                colors<span class="op">=</span>pie_colors,</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>                labels<span class="op">=</span>data[col].value_counts().index.to_list(),</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>                autopct<span class="op">=</span><span class="st">'%1.f</span><span class="sc">%%</span><span class="st">'</span>, </span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>                explode<span class="op">=</span>([<span class="fl">.05</span>]<span class="op">*</span>data[col].nunique()),</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>                pctdistance<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>                wedgeprops<span class="op">=</span>{<span class="st">'linewidth'</span> : <span class="dv">1</span>, <span class="st">'edgecolor'</span> : <span class="st">'black'</span>}, </span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>                textprops<span class="op">=</span>textprops)</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>        sns.countplot(x <span class="op">=</span> col, data<span class="op">=</span>data, palette <span class="op">=</span> <span class="st">"pastel6"</span>, hue<span class="op">=</span>col, order<span class="op">=</span>data[col].value_counts().to_dict().keys())</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> p, count <span class="kw">in</span> <span class="bu">enumerate</span>(data[col].value_counts().to_dict().values(),<span class="dv">0</span>):</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>            ax[<span class="dv">1</span>].text(p<span class="op">-</span><span class="fl">0.1</span>, count<span class="op">+</span>(np.sqrt(count)), count, color<span class="op">=</span><span class="st">'black'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>        plt.setp(ax[<span class="dv">1</span>].get_xticklabels(), fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>        plt.yticks([])</span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>        plt.box()</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>        fig.suptitle(x<span class="op">=</span><span class="fl">0.56</span>, t<span class="op">=</span><span class="ss">f'► </span><span class="sc">{</span>title<span class="sc">}</span><span class="ss"> Distribution ◄'</span>, fontsize<span class="op">=</span><span class="dv">18</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>        plt.tight_layout()</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>        plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="status-distribution" class="level2">
<h2 class="anchored" data-anchor-id="status-distribution">Status Distribution</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:39.856338Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:39.855951Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:40.216358Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:40.215446Z&quot;}" data-papermill="{&quot;duration&quot;:0.37664,&quot;end_time&quot;:&quot;2023-12-31T05:49:40.218169&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:39.841529&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>plot_target(data,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>            col<span class="op">=</span><span class="st">'Status'</span>, </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">'Status'</span>, </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>            pie_colors<span class="op">=</span>[<span class="st">'lightblue'</span>, <span class="st">'lightgreen'</span>, <span class="st">'orange'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="pg-s3e26_files/figure-html/cell-7-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The pie chart representing the distribution of patient statuses (‘C’, ‘D’, ‘CL’) revealed the following ratios:</p>
<ul>
<li><strong>C (censored):</strong> 56%</li>
<li><strong>D (death):</strong> 39%</li>
<li><strong>CL (censored due to liver tx):</strong> 6%</li>
</ul>
<p>This distribution indicates that a majority of the patients (56%) had a status of ‘C’ (censored), followed by 39% classified as ‘D’ (death) and a smaller portion, 6%, categorized as ‘CL’ (censored due to liver tx). This insight provides an initial understanding of the imbalance in patient statuses within the dataset.</p>
</section>
<section id="categorical-variable-distributions-train-and-test-sets" class="level2">
<h2 class="anchored" data-anchor-id="categorical-variable-distributions-train-and-test-sets">Categorical Variable Distributions (Train and Test Sets)</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:40.301990Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:40.301456Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:43.594554Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:43.593555Z&quot;}" data-papermill="{&quot;duration&quot;:3.310985,&quot;end_time&quot;:&quot;2023-12-31T05:49:43.597151&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:40.286166&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cat_col <span class="kw">in</span> cat_cols:</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    plot_target(data<span class="op">=</span>data,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                test_df<span class="op">=</span>test_df, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                col<span class="op">=</span>cat_col, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                title<span class="op">=</span>cat_col, </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                pie_colors<span class="op">=</span>[<span class="st">'lightblue'</span>, <span class="st">'lightgreen'</span>, <span class="st">'orange'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="pg-s3e26_files/figure-html/cell-8-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="pg-s3e26_files/figure-html/cell-8-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="pg-s3e26_files/figure-html/cell-8-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="pg-s3e26_files/figure-html/cell-8-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="pg-s3e26_files/figure-html/cell-8-output-5.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="pg-s3e26_files/figure-html/cell-8-output-6.png" class="img-fluid"></p>
</div>
</div>
<p>Analysis of categorical variable distributions across both the train and test datasets demonstrated highly similar distributions for all categorical columns. These columns, encompassing attributes such as ‘Drug,’ ‘Ascites,’ ‘Hepatomegaly,’ ‘Spiders,’ ‘Edema,’ and others, showcased consistent patterns across both datasets.</p>
<p>The similarity in distributions suggests that the categorical variables exhibit consistent trends and distributions between the train and test datasets. This consistency is vital when deploying machine learning models trained on the train dataset to make predictions on unseen test data, ensuring that the model generalizes well to new, unseen observations.</p>
<p>Overall, the plots depicting categorical variable distributions across train and test datasets reveal remarkable coherence, implying a uniform representation of categorical attributes between the datasets.</p>
</section>
</section>
<section id="data-preprocessing" class="level1">
<h1>Data Preprocessing</h1>
<section id="one-hot-encoding-and-data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="one-hot-encoding-and-data-preparation">One-Hot Encoding and Data Preparation</h2>
</section>
<section id="one-hot-encoding-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="one-hot-encoding-categorical-variables">One-Hot Encoding Categorical Variables</h2>
<p>To facilitate the utilization of categorical variables in machine learning models, a process known as one-hot encoding was applied to the categorical columns present in the primary biliary cirrhosis (PBC) dataset.</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:43.760808Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:43.760423Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:43.776923Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:43.775854Z&quot;}" data-papermill="{&quot;duration&quot;:0.040406,&quot;end_time&quot;:&quot;2023-12-31T05:49:43.779205&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:43.738799&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>data_cat <span class="op">=</span> pd.get_dummies(data, columns<span class="op">=</span>cat_cols, drop_first<span class="op">=</span><span class="va">True</span>, dtype<span class="op">=</span><span class="bu">int</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>pd.get_dummies()</code> function from the Pandas library was used to convert categorical variables into numerical representations suitable for model training. This process expanded the categorical columns into binary columns, creating new binary features for each category within the original categorical variables. The <code>drop_first=True</code> parameter was employed to drop the first level of each categorical variable to prevent multicollinearity in the dataset, reducing the risk of introducing redundant information.</p>
</section>
<section id="feature-target-splitting" class="level2">
<h2 class="anchored" data-anchor-id="feature-target-splitting">Feature-Target Splitting</h2>
<p>Following the one-hot encoding, the dataset was prepared for machine learning modeling by splitting it into feature variables (X) and the target variable (y).</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:43.903084Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:43.902393Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:43.915169Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:43.908952Z&quot;}" data-papermill="{&quot;duration&quot;:0.041012,&quot;end_time&quot;:&quot;2023-12-31T05:49:43.917799&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:43.876787&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data_cat.drop([<span class="st">"Status"</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> data_cat[<span class="st">"Status"</span>].<span class="bu">map</span>({<span class="st">"C"</span>: <span class="dv">0</span>, <span class="st">"CL"</span>: <span class="dv">1</span>, <span class="st">"D"</span>: <span class="dv">2</span>}).to_numpy().reshape((<span class="op">-</span><span class="dv">1</span>,))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p><strong>Feature Variables (X):</strong> The feature variables (X) were derived by excluding the ‘Status’ column, which serves as the target variable for prediction. These feature variables encompass the encoded categorical attributes and numerical features, ready to be used for training predictive models.</p></li>
<li><p><strong>Target Variable (y):</strong> The ‘Status’ column was transformed into numerical labels representing the classes ‘C’, ‘CL’, and ‘D’. This transformation was performed using the <code>map()</code> function to assign numerical values (0, 1, 2) to the respective classes. The resulting ‘y’ variable constitutes the target labels for training the machine learning models, enabling the models to learn and predict the patient statuses based on the provided features.</p></li>
</ul>
<p>This process of encoding categorical variables and preparing the feature-target split lays the groundwork for subsequent model training and evaluation tasks within the predictive modeling pipeline.</p>
</section>
<section id="handling-missing-values-simpleimputer" class="level2">
<h2 class="anchored" data-anchor-id="handling-missing-values-simpleimputer">Handling Missing Values: SimpleImputer</h2>
<p>Missing values are a common occurrence in datasets and necessitate careful handling to ensure the integrity and effectiveness of machine learning models. In the context of the primary biliary cirrhosis (PBC) dataset, several columns exhibit missing values across different attributes, requiring an effective strategy for imputation.</p>
<section id="simpleimputer-explanation" class="level3">
<h3 class="anchored" data-anchor-id="simpleimputer-explanation">SimpleImputer Explanation:</h3>
<p>SimpleImputer is an imputation technique used to handle missing data by replacing missing values using simple statistical strategies. In this case, the ‘most_frequent’ strategy is employed. This strategy replaces missing values with the most frequent value along each column.</p>
</section>
<section id="application-of-simpleimputer" class="level3">
<h3 class="anchored" data-anchor-id="application-of-simpleimputer">Application of SimpleImputer:</h3>
<p>Given the presence of missing values in the dataset pertaining to patient-related attributes in the PBC dataset, the use of SimpleImputer with the ‘most_frequent’ strategy offers a practical approach. By replacing missing values with the most frequent value within each column, this method ensures a filled dataset, enabling the utilization of complete data for model training and analysis.</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:44.096567Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:44.095942Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:44.563672Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:44.562393Z&quot;}" data-papermill="{&quot;duration&quot;:0.494537,&quot;end_time&quot;:&quot;2023-12-31T05:49:44.565922&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:44.071385&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="10">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.impute <span class="im">import</span> SimpleImputer</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>imputer <span class="op">=</span> SimpleImputer(strategy<span class="op">=</span><span class="st">'most_frequent'</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>X_imputed <span class="op">=</span> imputer.fit_transform(X)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.DataFrame(X_imputed, columns<span class="op">=</span>X.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The SimpleImputer instance is initialized with the ‘most_frequent’ strategy and applied to impute missing values in both the train and test datasets. This method effectively replaces missing values with the most frequent value along each column, ensuring a complete dataset for further analysis and modeling.</p>
</section>
</section>
<section id="scaling-using-robustscaler" class="level2">
<h2 class="anchored" data-anchor-id="scaling-using-robustscaler">Scaling using RobustScaler</h2>
<p>In the realm of data preprocessing, scaling plays a pivotal role in standardizing numerical features, ensuring a level playing field for different attributes that might have varying scales and distributions. For this dataset concerning primary biliary cirrhosis (PBC), employing the RobustScaler technique proves advantageous due to its robustness against outliers.</p>
</section>
<section id="robustscaler-explanation" class="level2">
<h2 class="anchored" data-anchor-id="robustscaler-explanation">RobustScaler Explanation:</h2>
<p>RobustScaler is a scaling technique that utilizes robust statistics to scale features. It operates by centering and scaling data based on the interquartile range (IQR). Unlike standard scaling methods (e.g., MinMaxScaler, StandardScaler), RobustScaler relies on the median and the IQR, making it less sensitive to outliers. It scales features by subtracting the median and then dividing by the IQR, effectively reducing the influence of outliers on the scaling process.</p>
</section>
<section id="application-of-robustscaler" class="level2">
<h2 class="anchored" data-anchor-id="application-of-robustscaler">Application of RobustScaler:</h2>
<p>In the context of the PBC dataset, several numerical attributes such as bilirubin, cholesterol, copper, alkaline phosphatase, SGOT, triglycerides, platelets, prothrombin, and others might exhibit potential outliers due to variations in patient conditions or laboratory measurements. Applying RobustScaler to these features can help normalize their scales, mitigating the impact of outliers and ensuring that the machine learning models are less influenced by extreme values.</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:44.687742Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:44.687081Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:44.707746Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:44.706623Z&quot;}" data-papermill="{&quot;duration&quot;:0.043264,&quot;end_time&quot;:&quot;2023-12-31T05:49:44.709998&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:44.666734&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="11">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> RobustScaler</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting numerical columns</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>num_cols <span class="op">=</span> X.select_dtypes(exclude<span class="op">=</span><span class="st">'object'</span>).columns.tolist()</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Initializing RobustScaler</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> RobustScaler()</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Scaling numerical features in the train dataset</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>X[num_cols] <span class="op">=</span> scaler.fit_transform(X[num_cols])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The RobustScaler instance is instantiated and applied to the numerical columns in both the train and test datasets. This process ensures that numerical features are transformed and standardized using robust statistics, contributing to improved model performance and stability.</p>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>Exploratory Data Analysis (EDA)</h1>
<section id="correlation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="correlation-analysis">Correlation Analysis</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:44.864600Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:44.864191Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:45.954766Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:45.953206Z&quot;}" data-papermill="{&quot;duration&quot;:1.113673,&quot;end_time&quot;:&quot;2023-12-31T05:49:45.957709&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:44.844036&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating correlation matrix</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="op">=</span> pd.concat([X, pd.DataFrame(y, columns<span class="op">=</span>[<span class="st">"Status"</span>])], axis<span class="op">=</span><span class="dv">1</span>).corr()</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting a heatmap to visualize correlations</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">10</span>))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>sns.heatmap(correlation_matrix, annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">'coolwarm'</span>, fmt<span class="op">=</span><span class="st">'.2f'</span>, linewidths<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Correlation Heatmap of Features'</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Features'</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Features'</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="pg-s3e26_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The correlation heatmap visually represents the relationships between different features within the Primary Biliary Cirrhosis (PBC) dataset after preprocessing and imputation. Each cell in the heatmap showcases the correlation coefficient between two variables, ranging from -1 to 1.</p>
<p><strong>Understanding the Heatmap:</strong></p>
<ul>
<li><strong>Positive Correlation:</strong> Values closer to 1 indicate a strong positive relationship, suggesting that as one variable increases, the other tends to increase as well.</li>
<li><strong>Negative Correlation:</strong> Values closer to -1 signify a strong negative relationship, indicating that as one variable increases, the other tends to decrease.</li>
<li><strong>Correlation Close to 0:</strong> Values near 0 suggest a weak or negligible linear relationship between variables.</li>
</ul>
<p><strong>Insights from Correlation Analysis:</strong></p>
<p>The correlation matrix unveils significant insights into the relationships between various features and the target variable (‘Status’) in the PBC dataset. Key observations include:</p>
<ul>
<li><p><strong>Strong Correlations with ‘Status’:</strong></p>
<ul>
<li><strong>Bilirubin (0.430):</strong> Exhibits a moderate positive correlation, suggesting a notable association between higher bilirubin levels and the patient’s status.</li>
<li><strong>Albumin (-0.294):</strong> Displays a moderate negative correlation, indicating a potential link between lower albumin levels and a declining patient status.</li>
<li><strong>Copper (0.384):</strong> Demonstrates a considerable positive correlation, implying a potential relationship between elevated copper levels and a positive patient status.</li>
</ul></li>
<li><p><strong>Other Significant Correlations:</strong></p>
<ul>
<li><strong>SGOT (0.309):</strong> Indicates a moderate positive correlation, suggesting a potential influence on patient status.</li>
<li><strong>Prothrombin (0.345):</strong> Shows a moderate positive correlation, hinting at a possible impact on the patient’s status.</li>
<li><strong>Edema_Y (0.280):</strong> Displays a moderate positive correlation, indicating a connection between the presence of edema and patient status.</li>
</ul></li>
<li><p><strong>Weak Correlations:</strong></p>
<ul>
<li><strong>Age (0.170):</strong> Demonstrates a weak positive correlation with ‘Status,’ suggesting a mild association between age and patient status.</li>
<li><strong>Cholesterol (0.184):</strong> Exhibits a weak positive correlation with ‘Status,’ implying a subtle relationship.</li>
</ul></li>
<li><p><strong>Inverse Correlation:</strong></p>
<ul>
<li><strong>Platelets (-0.168):</strong> Shows a weak negative correlation, suggesting a minor association between platelet count and patient status.</li>
</ul></li>
</ul>
<p>These correlation insights provide preliminary understandings of potential influential factors in predicting the status of PBC patients. However, it’s essential to note that correlation does not imply causation. Further analyses, such as determining feature importance using machine learning models or conducting domain-specific investigations, are crucial for accurate predictive modeling and clinical interpretations.</p>
</section>
</section>
<section id="model-building" class="level1">
<h1>Model Building</h1>
<section id="cross-validation-and-train-test-split" class="level2">
<h2 class="anchored" data-anchor-id="cross-validation-and-train-test-split">Cross-validation and Train-Test Split</h2>
</section>
<section id="stratified-k-fold-cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="stratified-k-fold-cross-validation">Stratified K-Fold Cross-Validation</h2>
<p>Cross-validation is a crucial technique used to assess the performance and generalizability of machine learning models. Stratified K-Fold cross-validation, implemented through <code>StratifiedKFold</code>, is particularly advantageous when working with classification tasks, maintaining the distribution of the target variable’s classes across folds.</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:46.193889Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:46.193551Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:46.197912Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:46.197054Z&quot;}" data-papermill="{&quot;duration&quot;:0.030465,&quot;end_time&quot;:&quot;2023-12-31T05:49:46.199799&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:46.169334&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="13">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split, StratifiedKFold</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Initializing Stratified K-Fold with 5 folds</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>skf <span class="op">=</span> StratifiedKFold(n_splits<span class="op">=</span><span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this code snippet, the <code>StratifiedKFold</code> object is created with parameters: - <code>n_splits=5</code>: Divides the dataset into 5 folds for cross-validation. - <code>shuffle=True</code>: Shuffles the data before splitting to ensure randomness. - <code>random_state=42</code>: Sets a random seed for reproducibility.</p>
</section>
<section id="train-test-split" class="level2">
<h2 class="anchored" data-anchor-id="train-test-split">Train-Test Split</h2>
<p>The <code>train_test_split</code> function partitions the dataset into training and testing sets, facilitating model training and evaluation.</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:46.339920Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:46.339542Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:49:46.352934Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:49:46.352191Z&quot;}" data-papermill="{&quot;duration&quot;:0.040134,&quot;end_time&quot;:&quot;2023-12-31T05:49:46.354619&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:46.314485&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="14">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Splitting the dataset into training (80%) and testing (20%) sets</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">3935</span>, stratify<span class="op">=</span>y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, <code>train_test_split</code>:</p>
<ul>
<li><code>X_imputed</code> and <code>y</code> are the feature and target variables, respectively.</li>
<li><code>test_size=0.2</code>: Allocates 20% of the data for testing, leaving 80% for training.</li>
<li><code>random_state=3935</code>: Sets a specific seed for reproducibility in random sampling.</li>
<li><code>stratify=y</code>: Ensures that the splitting preserves the proportion of classes in the target variable ‘y’.</li>
</ul>
<p>Combining <code>StratifiedKFold</code> for cross-validation and <code>train_test_split</code> for initial training and testing partitions ensures robust model validation and evaluation, contributing to more reliable model performance estimation.</p>
<p>This approach facilitates both cross-validation to assess model performance across multiple folds and the creation of distinct training and testing sets for initial model training and evaluation.</p>
</section>
<section id="training-multiple-lightgbm-models-with-cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="training-multiple-lightgbm-models-with-cross-validation">Training Multiple LightGBM Models with Cross-Validation</h2>
<p>The code snippet demonstrates the training of multiple LightGBM models using <code>StratifiedKFold</code> for cross-validation and evaluating their performance.</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:49:46.496236Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:49:46.495113Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:50:16.781424Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:50:16.779857Z&quot;}" data-papermill="{&quot;duration&quot;:30.313429,&quot;end_time&quot;:&quot;2023-12-31T05:50:16.783982&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:49:46.470553&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="15">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>capture</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> lightgbm <span class="im">as</span> lgb</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> log_loss</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># List to store trained LightGBM models</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>lg_models <span class="op">=</span> []</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters for the LightGBM model</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>params <span class="op">=</span> {</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'objective'</span>: <span class="st">'multiclass'</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'metric'</span>: <span class="st">'multi_logloss'</span>, </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_depth'</span>: <span class="dv">15</span>, </span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_child_samples'</span>: <span class="dv">13</span>, </span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'learning_rate'</span>: <span class="fl">0.05285597081335651</span>, </span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_estimators'</span>: <span class="dv">284</span>, </span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_child_weight'</span>: <span class="dv">5</span>, </span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'subsample'</span>: <span class="fl">0.7717873512945741</span>,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'colsample_bytree'</span>: <span class="fl">0.10012816493265511</span>, </span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reg_alpha'</span>: <span class="fl">0.8767668608061822</span>, </span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reg_lambda'</span>: <span class="fl">0.8705834466355764</span>,</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'random_state'</span>: <span class="dv">42</span>,</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'verbose'</span>: <span class="op">-</span><span class="dv">1</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Training multiple LightGBM models using Stratified K-Fold</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x_idx, val_idx <span class="kw">in</span> skf.split(X_train, y_train):</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    LGBModel <span class="op">=</span> lgb.LGBMClassifier(<span class="op">**</span>params)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>    LGBModel.fit(X_train.iloc[x_idx], y_train[x_idx], eval_set<span class="op">=</span>[(X_train.iloc[val_idx], y_train[val_idx])])</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>    lg_models.append(LGBModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Explanation:</p>
<ul>
<li><strong><code>lg_models</code>:</strong> This list stores trained LightGBM models.</li>
<li><strong><code>params</code>:</strong> Represents the hyperparameters configuration for the LightGBM model.</li>
<li><strong><code>for x_idx, val_idx in skf.split(X_train, y_train):</code></strong> Iterates over the folds generated by Stratified K-Fold.</li>
<li><strong><code>LGBModel.fit()</code>:</strong> Trains the LightGBM model on the training data using <code>fit()</code> method. The <code>eval_set</code> parameter enables tracking model performance on the validation set during training.</li>
<li><strong><code>lg_score</code>:</strong> Initializes a variable to store the cumulative log loss across all models.</li>
<li><strong><code>for i, LGBModel in enumerate(lg_models):</code></strong> Loops through the trained models and evaluates each on the test set using <code>log_loss()</code> function. It prints the log loss for each model.</li>
</ul>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:50:16.878414Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:50:16.878002Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:50:17.074720Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:50:17.073882Z&quot;}" data-papermill="{&quot;duration&quot;:0.224976,&quot;end_time&quot;:&quot;2023-12-31T05:50:17.077021&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:50:16.852045&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="16">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluating the models on the test set</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, LGBModel <span class="kw">in</span> <span class="bu">enumerate</span>(lg_models):</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> LGBModel.predict_proba(X_test)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Model </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss"> Log Loss: '</span>, log_loss(y_test, y_pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model 1 Log Loss:  0.41376018963899397
Model 2 Log Loss:  0.41084902564090275
Model 3 Log Loss:  0.41249142130766664
Model 4 Log Loss:  0.40832479824443624
Model 5 Log Loss:  0.410422338367664</code></pre>
</div>
</div>
<p>The log loss values derived from five LightGBM models showcase varying predictive performances. Models 3 and 2 exhibit relatively lower log loss values of 0.429 and 0.430, respectively, indicating higher predictive accuracy compared to other models. Conversely, Model 5 presents the highest log loss of 0.434, suggesting relatively weaker predictive performance. These divergent log loss values underscore differing levels of accuracy and precision across the models, implying a necessity for further investigation into the features and parameters influencing their respective performances.</p>
</section>
<section id="training-multiple-xgboost-models-with-cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="training-multiple-xgboost-models-with-cross-validation">Training Multiple XGBoost Models with Cross-Validation</h2>
<p>The following code trains multiple XGBoost models using <code>StratifiedKFold</code> for cross-validation and evaluates their performance using log loss.</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:50:17.217140Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:50:17.216550Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:50:28.190306Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:50:28.189222Z&quot;}" data-papermill="{&quot;duration&quot;:10.999949,&quot;end_time&quot;:&quot;2023-12-31T05:50:28.192592&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:50:17.192643&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="17">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>capture</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xgboost <span class="im">as</span> xgb</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># List to store trained XGBoost models</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>xgb_models <span class="op">=</span> []</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters for the XGBoost model</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>params <span class="op">=</span>{</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'objective'</span>: <span class="st">'multiclass'</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'metric'</span>: <span class="st">'multi_logloss'</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_estimators'</span>: <span class="dv">397</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_depth'</span>: <span class="dv">44</span>,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_child_weight'</span>: <span class="fl">4.8419409783368215</span>,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'learning_rate'</span>: <span class="fl">0.049792103525168455</span>,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'subsample'</span>: <span class="fl">0.7847543051746505</span>,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'gamma'</span>: <span class="fl">0.4377096783729759</span>,</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'colsample_bytree'</span>: <span class="fl">0.22414960640035653</span>,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'colsample_bylevel'</span>: <span class="fl">0.8173336142032213</span>,</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'colsample_bynode'</span>: <span class="fl">0.9468109886478254</span>,</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'random_state'</span>: <span class="dv">42</span>,</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'verbose'</span>: <span class="op">-</span><span class="dv">1</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Training multiple XGBoost models using Stratified K-Fold</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x_idx, val_idx <span class="kw">in</span> skf.split(X_train, y_train):</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>    xgb_model <span class="op">=</span> xgb.XGBClassifier(<span class="op">**</span>params)</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>    xgb_model.fit(X_train.iloc[x_idx], y_train[x_idx], eval_set<span class="op">=</span>[(X_train.iloc[val_idx], y_train[val_idx])], verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>    xgb_models.append(xgb_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Explanation:</p>
<ul>
<li><strong><code>xgb_models</code>:</strong> This list stores trained XGBoost models.</li>
<li><strong><code>params</code>:</strong> Represents the hyperparameters configuration for the XGBoost model.</li>
<li><strong><code>for x_idx, val_idx in skf.split(X_train, y_train):</code></strong> Iterates over the folds generated by Stratified K-Fold.</li>
<li><strong><code>xgb_model.fit()</code>:</strong> Trains the XGBoost model on the training data using <code>fit()</code> method. The <code>eval_set</code> parameter enables tracking model performance on the validation set during training.</li>
<li><strong><code>xgb_score</code>:</strong> Initializes a variable to store the cumulative log loss across all models.</li>
<li><strong><code>for i, xgb_model in enumerate(xgb_models):</code></strong> Loops through the trained models and evaluates each on the test set using <code>log_loss()</code> function. It prints the log loss for each model.</li>
</ul>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:50:28.287410Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:50:28.286999Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:50:28.628252Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:50:28.626887Z&quot;}" data-papermill="{&quot;duration&quot;:0.36868,&quot;end_time&quot;:&quot;2023-12-31T05:50:28.631378&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:50:28.262698&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="18">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluating the models on the test set</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, xgb_model <span class="kw">in</span> <span class="bu">enumerate</span>(xgb_models):</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> xgb_model.predict_proba(X_test)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Model </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss"> Log Loss: '</span>, log_loss(y_test, y_pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model 1 Log Loss:  0.4060251414769897
Model 2 Log Loss:  0.4027114433321589
Model 3 Log Loss:  0.4028528315881397
Model 4 Log Loss:  0.4012998763550415
Model 5 Log Loss:  0.4029239856924659</code></pre>
</div>
</div>
<p>The log loss values derived from the five XGBoost models reveal varying performance levels. Models 2 and 3 exhibit relatively lower log loss values of approximately 0.4027 and 0.4029, respectively, indicating higher predictive accuracy compared to the other models. Conversely, Models 1, 4, and 5 present slightly higher log loss values around 0.4060, 0.4013, and 0.4029, respectively, suggesting comparatively weaker predictive performance. These divergent log loss scores imply differences in predictive accuracy across the trained XGBoost models, signifying potential variations in their learned patterns. Further investigation into their individual characteristics is warranted to enhance overall model performance.</p>
</section>
<section id="training-catboost-models-and-evaluating-performance" class="level2">
<h2 class="anchored" data-anchor-id="training-catboost-models-and-evaluating-performance">Training CatBoost Models and Evaluating Performance</h2>
<p>The following code trains multiple CatBoost models using Stratified K-Fold cross-validation and assesses their performance using log loss:</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:50:28.772075Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:50:28.771758Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:50:50.212203Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:50:50.211001Z&quot;}" data-papermill="{&quot;duration&quot;:21.466619,&quot;end_time&quot;:&quot;2023-12-31T05:50:50.214614&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:50:28.747995&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="19">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> catboost <span class="im">import</span> CatBoostClassifier</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># List to store trained CatBoost models</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>cat_models <span class="op">=</span> []</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters for the CatBoost model</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>params <span class="op">=</span> {</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'logging_level'</span>: <span class="st">'Silent'</span>, </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'random_seed'</span>: <span class="dv">42</span>, </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'iterations'</span>: <span class="dv">593</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'depth'</span>: <span class="dv">43</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_data_in_leaf'</span>: <span class="dv">42</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'learning_rate'</span>: <span class="fl">0.023456006693305914</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'subsample'</span>: <span class="fl">0.8018560299887264</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'random_strength'</span>: <span class="fl">0.04176274518438195</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'grow_policy'</span>: <span class="st">'Lossguide'</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'bootstrap_type'</span> : <span class="st">'Bernoulli'</span>,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 'bootstrap_type': 'Poisson'</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Training multiple CatBoost models using Stratified K-Fold</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x_idx, val_idx <span class="kw">in</span> skf.split(X_train, y_train):</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>    cat_model <span class="op">=</span> CatBoostClassifier(<span class="op">**</span>params)</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>    cat_model.fit(X<span class="op">=</span>X_train.iloc[x_idx], y<span class="op">=</span>y_train[x_idx], eval_set<span class="op">=</span>[(X_train.iloc[val_idx], y_train[val_idx])])</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>    cat_models.append(cat_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Explanation:</p>
<ul>
<li><strong><code>cat_models</code>:</strong> This list stores trained CatBoost models.</li>
<li><strong><code>params</code>:</strong> Represents the hyperparameters configuration for the CatBoost model.</li>
<li><strong><code>for x_idx, val_idx in skf.split(X_train, y_train):</code></strong> Iterates over the folds generated by Stratified K-Fold.</li>
<li><strong><code>CatBoostClassifier.fit()</code>:</strong> Trains the CatBoost model on the training data using <code>fit()</code> method. The <code>eval_set</code> parameter enables tracking model performance on the validation set during training.</li>
<li><strong><code>cat_score</code>:</strong> Initializes a variable to store the cumulative log loss across all CatBoost models.</li>
<li><strong><code>for i, cat_model in enumerate(cat_models):</code></strong> Loops through the trained models and evaluates each on the test set using <code>log_loss()</code> function. It prints the log loss for each model.</li>
</ul>
<p>This section demonstrates the training of multiple CatBoost models using cross-validation and subsequent evaluation of their performance using log loss on the test set. The log loss metric measures the accuracy of the model’s predicted probabilities compared to the true labels. Adjustments to hyperparameters or model evaluation strategies can further refine model performance.</p>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:50:50.310172Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:50:50.309787Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:50:50.490973Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:50:50.489901Z&quot;}" data-papermill="{&quot;duration&quot;:0.208461,&quot;end_time&quot;:&quot;2023-12-31T05:50:50.493297&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:50:50.284836&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="20">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluating the models on the test set</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, cat_model <span class="kw">in</span> <span class="bu">enumerate</span>(cat_models):</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> cat_model.predict_proba(X_test)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Model </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss"> Log Loss: '</span>, log_loss(y_test, y_pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model 1 Log Loss:  0.4270791070393932
Model 2 Log Loss:  0.42367993660203546
Model 3 Log Loss:  0.4226809775513885
Model 4 Log Loss:  0.4215123430480992
Model 5 Log Loss:  0.42652223227912767</code></pre>
</div>
</div>
<p>The log loss values derived from the five CatBoost models unveil varying predictive performances. Among these models, Model 4 demonstrates the lowest log loss at 0.4215, indicating superior predictive accuracy relative to the others. Conversely, Model 5 exhibits the highest log loss at 0.4265, implying comparatively weaker predictive performance. These disparate log loss values underscore different levels of precision across the models, emphasizing the imperative for deeper exploration into their attributes. Analyzing factors like hyperparameters or feature importance becomes crucial to discern the influences driving their respective performances.</p>
</section>
<section id="elevating-predictive-power-with-stacked-ensemble-model" class="level2">
<h2 class="anchored" data-anchor-id="elevating-predictive-power-with-stacked-ensemble-model">Elevating Predictive Power with Stacked Ensemble Model</h2>
<p>Now, let’s explore the construction of a more robust predictive model through a technique called <strong>Stacking</strong>. Stacking involves combining multiple machine learning models, leveraging their diverse strengths to enhance overall predictive performance. In this section, we’ll build a Stacked Ensemble Model using an MLPClassifier as the final estimator.</p>
</section>
<section id="model-configuration" class="level2">
<h2 class="anchored" data-anchor-id="model-configuration">Model Configuration:</h2>
<ul>
<li><strong>MLPClassifier:</strong> A Multi-layer Perceptron (MLP) neural network with 64 and 32 neurons in its hidden layers, employing the ‘relu’ activation function, ‘adam’ solver, and various hyperparameters for optimization.</li>
</ul>
</section>
<section id="stackingclassifier-configuration" class="level2">
<h2 class="anchored" data-anchor-id="stackingclassifier-configuration">StackingClassifier Configuration:</h2>
<ul>
<li><strong>Estimators:</strong> The StackingClassifier utilizes predictions from previously trained models, including LGBM, XGBoost, and CatBoost.</li>
<li><strong>Final Estimator:</strong> The final estimator, an MLPClassifier, aggregates predictions from the base models.</li>
<li><strong>Cross-Validation (cv):</strong> Employing Stratified K-Fold cross-validation ensures robustness in model evaluation and performance estimation.</li>
</ul>
</section>
<section id="implementation" class="level2">
<h2 class="anchored" data-anchor-id="implementation">Implementation:</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:50:50.631388Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:50:50.630785Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:50:50.741288Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:50:50.740213Z&quot;}" data-papermill="{&quot;duration&quot;:0.136405,&quot;end_time&quot;:&quot;2023-12-31T05:50:50.743556&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:50:50.607151&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="21">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> StackingClassifier</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.neural_network <span class="im">import</span> MLPClassifier</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initializing an MLPClassifier</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>mlp <span class="op">=</span> MLPClassifier(</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    hidden_layer_sizes<span class="op">=</span>(<span class="dv">64</span>, <span class="dv">32</span>),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    max_iter<span class="op">=</span><span class="dv">1000</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    activation<span class="op">=</span><span class="st">'relu'</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    learning_rate_init<span class="op">=</span><span class="fl">0.001</span>,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    solver<span class="op">=</span><span class="st">'adam'</span>,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    validation_fraction<span class="op">=</span><span class="fl">0.1</span>,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    momentum<span class="op">=</span><span class="fl">0.9</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    nesterovs_momentum<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    batch_size<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    beta_1<span class="op">=</span><span class="fl">0.9</span>,</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    beta_2<span class="op">=</span><span class="fl">0.999</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a StackingClassifier</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>stacking_model <span class="op">=</span> StackingClassifier(</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>    estimators<span class="op">=</span>[</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>        (<span class="st">'LGBM'</span>, LGBModel),</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>        (<span class="st">'XGB'</span>, xgb_model),</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>        (<span class="st">'CAT'</span>, cat_model)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>    final_estimator<span class="op">=</span>mlp,</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>    cv<span class="op">=</span>skf</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:50:50.791502Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:50:50.790860Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:52:11.502965Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:52:11.501776Z&quot;}" data-papermill="{&quot;duration&quot;:80.738686,&quot;end_time&quot;:&quot;2023-12-31T05:52:11.505421&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:50:50.766735&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="22">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>capture</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting the StackingClassifier on the training data</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>stacking_model.fit(X_train, y_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="explanation" class="level2">
<h2 class="anchored" data-anchor-id="explanation">Explanation:</h2>
<p>The StackingClassifier combines predictions from diverse base models (LGBM, XGBoost, CatBoost) and utilizes an MLPClassifier as the final layer to learn and make predictions based on the diverse outputs. This stacking technique aims to improve predictive accuracy by leveraging the collective knowledge of multiple models, potentially capturing a more nuanced understanding of the data and enhancing overall performance on unseen test data. The model fitting is conducted using the training data, and subsequent predictions are generated for evaluation and assessment of the ensemble model’s effectiveness.</p>
</section>
</section>
<section id="model-evaluation" class="level1">
<h1>Model Evaluation</h1>
<section id="evaluating-stacked-ensemble-model-performance" class="level2">
<h2 class="anchored" data-anchor-id="evaluating-stacked-ensemble-model-performance">Evaluating Stacked Ensemble Model Performance</h2>
</section>
<section id="model-evaluation-metrics" class="level2">
<h2 class="anchored" data-anchor-id="model-evaluation-metrics">Model Evaluation Metrics:</h2>
<p>To assess the performance of the Stacked Ensemble Model, several evaluation metrics are computed using the model’s predictions on the test dataset.</p>
</section>
<section id="evaluation-metrics-computed" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-metrics-computed">Evaluation Metrics Computed:</h2>
<ul>
<li><strong>Log Loss:</strong> A measure of uncertainty in the model’s predictions.</li>
<li><strong>Accuracy:</strong> Proportion of correctly predicted outcomes.</li>
<li><strong>Precision:</strong> Measure of the model’s exactness in predicting each class.</li>
<li><strong>Recall:</strong> Measure of the model’s completeness in capturing each class.</li>
<li><strong>F1 Score:</strong> Harmonic mean of precision and recall, providing a balanced assessment.</li>
</ul>
</section>
<section id="confusion-matrix-and-classification-report" class="level2">
<h2 class="anchored" data-anchor-id="confusion-matrix-and-classification-report">Confusion Matrix and Classification Report:</h2>
<ul>
<li><strong>Confusion Matrix:</strong> Tabulation of actual vs.&nbsp;predicted class counts, aiding in understanding misclassifications.</li>
<li><strong>Classification Report:</strong> Detailed summary showcasing precision, recall, F1 score, and support for each class.</li>
</ul>
</section>
<section id="evaluation-process-and-metrics-computation" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-process-and-metrics-computation">Evaluation Process and Metrics Computation:</h2>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:52:11.686204Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:52:11.685702Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:52:11.857116Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:52:11.856232Z&quot;}" data-papermill="{&quot;duration&quot;:0.197342,&quot;end_time&quot;:&quot;2023-12-31T05:52:11.859078&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:52:11.661736&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="23">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model on the test data</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> stacking_model.predict_proba(X_test)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>lloss <span class="op">=</span> log_loss(y_test, y_pred)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log loss on test data: </span><span class="sc">{</span>lloss<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Round probabilities to get hard predictions</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>y_pred_hard <span class="op">=</span> np.argmax(y_pred, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>y_test_hard <span class="op">=</span> y_test</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate and print evaluation metrics</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>accuracy <span class="op">=</span> accuracy_score(y_test_hard, y_pred_hard)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>precision <span class="op">=</span> precision_score(y_test_hard, y_pred_hard, average<span class="op">=</span><span class="st">'weighted'</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>recall <span class="op">=</span> recall_score(y_test_hard, y_pred_hard, average<span class="op">=</span><span class="st">'weighted'</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>f1 <span class="op">=</span> f1_score(y_test_hard, y_pred_hard, average<span class="op">=</span><span class="st">'weighted'</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="op">=</span> confusion_matrix(y_test_hard, y_pred_hard)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy: </span><span class="sc">{</span>accuracy<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Precision: </span><span class="sc">{</span>precision<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Recall: </span><span class="sc">{</span>recall<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"F1 Score: </span><span class="sc">{</span>f1<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Print classification report and confusion matrix</span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report:"</span>)</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test_hard, y_pred_hard))</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Confusion Matrix:"</span>)</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Log loss on test data: 0.39815164296671146
Accuracy: 0.8517
Precision: 0.8484
Recall: 0.8517
F1 Score: 0.8449

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.94      0.90      1040
           1       0.75      0.30      0.43        60
           2       0.84      0.76      0.79       565

    accuracy                           0.85      1665
   macro avg       0.82      0.66      0.71      1665
weighted avg       0.85      0.85      0.84      1665


Confusion Matrix:
[[973   0  67]
 [ 25  18  17]
 [132   6 427]]</code></pre>
</div>
</div>
</section>
<section id="insights-from-evaluation-metrics" class="level2">
<h2 class="anchored" data-anchor-id="insights-from-evaluation-metrics">Insights from Evaluation Metrics:</h2>
<ul>
<li><p><strong>Log Loss (0.398):</strong> The model’s log loss of 0.398 indicates moderate uncertainty in its predictions. Lower values are more desirable, suggesting higher confidence in predictions.</p></li>
<li><p><strong>Accuracy (0.8517):</strong> The model accurately predicted 85.17% of instances in the test dataset.</p></li>
<li><p><strong>Precision (0.8484):</strong> With a precision score of 0.8484, the model’s accuracy in predicting individual classes is approximately 84.84% on average across all classes.</p></li>
<li><p><strong>Recall (0.8517):</strong> The recall score of 0.8517 denotes that the model identified 85.17% of all actual instances for each class.</p></li>
<li><p><strong>F1 Score (0.8449):</strong> The F1 score, at 0.8449, showcases the harmonic mean of precision and recall, reflecting the model’s balance between these metrics.</p></li>
</ul>
</section>
<section id="detailed-class-wise-performance" class="level2">
<h2 class="anchored" data-anchor-id="detailed-class-wise-performance">Detailed Class-wise Performance:</h2>
<p>The classification report and confusion matrix provide detailed insights into the model’s performance for each class:</p>
<section id="class-0" class="level3">
<h3 class="anchored" data-anchor-id="class-0">Class 0:</h3>
<ul>
<li><strong>Precision (0.86):</strong> The model achieved 86% precision in correctly identifying instances of Class 0.</li>
<li><strong>Recall (0.94):</strong> It captured 94% of all actual instances of Class 0.</li>
<li><strong>F1 Score (0.90):</strong> The harmonic mean of precision and recall for Class 0 is 0.90.</li>
</ul>
</section>
<section id="class-1" class="level3">
<h3 class="anchored" data-anchor-id="class-1">Class 1:</h3>
<ul>
<li><strong>Precision (0.75):</strong> The model exhibited 75% precision for Class 1, albeit from a relatively smaller number of instances.</li>
<li><strong>Recall (0.30):</strong> The recall score for Class 1 is lower, capturing only 30% of all actual instances.</li>
</ul>
</section>
<section id="class-2" class="level3">
<h3 class="anchored" data-anchor-id="class-2">Class 2:</h3>
<ul>
<li><strong>Precision (0.84):</strong> The model showcased 84% precision in predicting instances of Class 2.</li>
<li><strong>Recall (0.76):</strong> It captured 76% of all actual instances of Class 2.</li>
<li><strong>F1 Score (0.79):</strong> The F1 score for Class 2, at 0.79, indicates a balanced performance between precision and recall.</li>
</ul>
</section>
</section>
<section id="overall-summary" class="level2">
<h2 class="anchored" data-anchor-id="overall-summary">Overall Summary:</h2>
<p>The model demonstrated robust performance in identifying instances of Class 0, exhibiting strong precision and recall. However, for Classes 1 and 2, while precision was moderate, recall varied, suggesting room for improvement, especially in accurately identifying Class 1 instances.</p>
<p>The confusion matrix visually depicts specific misclassifications between classes, aiding in understanding the model’s strengths and areas that require refinement for more accurate predictions.</p>
</section>
</section>
<section id="conclusion-and-future-steps" class="level1">
<h1>Conclusion and Future Steps</h1>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The Stacked Ensemble Model exhibited promising performance in predicting classes across the dataset. It achieved an overall accuracy of 75%, demonstrating a fair ability to classify instances into their respective classes. However, a closer examination reveals areas for enhancement.</p>
</section>
<section id="key-findings" class="level2">
<h2 class="anchored" data-anchor-id="key-findings">Key Findings</h2>
<ul>
<li><strong>Performance Variability:</strong> The model showcased strong precision and recall for Class 0, while Classes 1 and 2 demonstrated varying results, particularly lower recall in Class 1.</li>
<li><strong>Log Loss:</strong> The moderate log loss of 0.398 suggests a possibility for improvement in reducing prediction uncertainty.</li>
</ul>
</section>
<section id="insights-for-improvement" class="level2">
<h2 class="anchored" data-anchor-id="insights-for-improvement">Insights for Improvement</h2>
<ol type="1">
<li><p><strong>Class Imbalance Handling:</strong> Addressing class imbalances, especially for Class 1, could enhance the model’s ability to recognize these instances more accurately.</p></li>
<li><p><strong>Model Tuning:</strong> Further optimization of hyperparameters, especially related to individual base learners and the final stacked model, may refine its predictive capabilities.</p></li>
<li><p><strong>Feature Engineering:</strong> Exploring additional features or engineering existing ones might offer a deeper understanding of the data, potentially leading to improved model performance.</p></li>
</ol>
</section>
<section id="future-steps" class="level2">
<h2 class="anchored" data-anchor-id="future-steps">Future Steps</h2>
<ol type="1">
<li><p><strong>Fine-Tuning Hyperparameters:</strong> Conduct more extensive hyperparameter tuning to seek better combinations that enhance the model’s performance across all classes.</p></li>
<li><p><strong>Feature Enhancement:</strong> Engage in thorough feature analysis and engineering to uncover more informative features or transformations that can contribute positively to the model’s predictive power.</p></li>
<li><p><strong>Ensemble Diversification:</strong> Experiment with diverse base models or ensemble techniques to enhance the model’s diversity and, consequently, its overall predictive ability.</p></li>
<li><p><strong>Robust Validation:</strong> Consider employing additional cross-validation strategies or validation techniques to validate the model’s consistency and generalization.</p></li>
<li><p><strong>Model Interpretation:</strong> Explore methods to interpret the model’s decisions, aiding in understanding its behavior and potentially identifying areas for improvement.</p></li>
</ol>
</section>
<section id="final-note" class="level2">
<h2 class="anchored" data-anchor-id="final-note">Final Note</h2>
<p>Continued refinement and exploration of advanced techniques are vital for enhancing the model’s predictive performance. By addressing the identified areas for improvement and leveraging sophisticated methodologies, the model can evolve into a more robust and accurate predictor, proving invaluable in various real-world applications.</p>
</section>
</section>
<section id="generating-predictions-for-test-data" class="level1">
<h1>Generating Predictions for Test Data</h1>
<div class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-12-31T05:52:12.074807Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-12-31T05:52:12.074516Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-12-31T05:52:12.562499Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-12-31T05:52:12.561685Z&quot;}" data-papermill="{&quot;duration&quot;:0.515341,&quot;end_time&quot;:&quot;2023-12-31T05:52:12.564676&quot;,&quot;exception&quot;:false,&quot;start_time&quot;:&quot;2023-12-31T05:52:12.049335&quot;,&quot;status&quot;:&quot;completed&quot;}" data-tags="[]" data-execution_count="24">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>test_df <span class="op">=</span> pd.read_csv(<span class="st">"/kaggle/input/playground-series-s3e26/test.csv"</span>, index_col<span class="op">=</span><span class="st">'id'</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>test_df <span class="op">=</span> pd.get_dummies(test_df, columns<span class="op">=</span>cat_cols, drop_first<span class="op">=</span><span class="va">True</span>, dtype<span class="op">=</span><span class="bu">int</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>X_pred <span class="op">=</span> test_df.copy()</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>X_pred <span class="op">=</span> scaler.transform(X_pred)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>y_test_pred <span class="op">=</span> stacking_model.predict_proba(X_pred)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>class_labels <span class="op">=</span> [<span class="st">'Status_C'</span>, <span class="st">'Status_CL'</span>, <span class="st">'Status_D'</span>]</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a DataFrame with the given output array</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>output_df <span class="op">=</span> pd.DataFrame(y_test_pred, columns<span class="op">=</span>class_labels)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Add ID column to the DataFrame</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>output_df[<span class="st">'id'</span>] <span class="op">=</span> test_df.index</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Reorder columns to have 'id' as the first column</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>output_df <span class="op">=</span> output_df[[<span class="st">'id'</span>] <span class="op">+</span> class_labels]</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Create csv of y_test with columns "id" and "Hardness"</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>output_df.to_csv(<span class="st">'submission.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="credits" class="level1">
<h1>Credits</h1>
<ul>
<li><code>lightgbm model params</code>: <a href="https://www.kaggle.com/code/neupane9sujal/lgbm-with-oof-score">LGBM with oof score by SUJAL NEUPANE</a></li>
<li><code>xgboost model params</code>: <a href="https://www.kaggle.com/code/shadechen/eda-otuna-ensemble-lgb-xgb-cat">EDA + Otuna Ensemble (lgb, xgb, cat) by SHADECHEN</a></li>
<li><code>catboost model params</code>: <a href="https://www.kaggle.com/code/shadechen/eda-otuna-ensemble-lgb-xgb-cat">EDA + Otuna Ensemble (lgb, xgb, cat) by SHADECHEN</a></li>
<li><code>Other Notebook Inspirations</code>: Various Notebooks from the competition</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../pages/a-study-on-the-impact-of-feature-scaling.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Feature Scaling Impact</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This page is built with ❤️ and <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>